// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: affected_area_reports.sql

package sqlcgen

import (
	"context"
)

const createAffectedAreaReport = `-- name: CreateAffectedAreaReport :one
INSERT INTO affected_area_reports (
    area_id,
    name,
    description,
    location_payload,
    severity,
    reporter_name,
    reporter_mobile
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, area_id, name, description, location_payload, severity, reporter_name, reporter_mobile, created_at
`

type CreateAffectedAreaReportParams struct {
	AreaID          int64                `json:"area_id"`
	Name            string               `json:"name"`
	Description     *string              `json:"description"`
	LocationPayload []byte               `json:"location_payload"`
	Severity        AffectedAreaSeverity `json:"severity"`
	ReporterName    *string              `json:"reporter_name"`
	ReporterMobile  *string              `json:"reporter_mobile"`
}

func (q *Queries) CreateAffectedAreaReport(ctx context.Context, arg CreateAffectedAreaReportParams) (AffectedAreaReport, error) {
	row := q.db.QueryRow(ctx, createAffectedAreaReport,
		arg.AreaID,
		arg.Name,
		arg.Description,
		arg.LocationPayload,
		arg.Severity,
		arg.ReporterName,
		arg.ReporterMobile,
	)
	var i AffectedAreaReport
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Name,
		&i.Description,
		&i.LocationPayload,
		&i.Severity,
		&i.ReporterName,
		&i.ReporterMobile,
		&i.CreatedAt,
	)
	return i, err
}

const getAffectedAreaReportByID = `-- name: GetAffectedAreaReportByID :one
SELECT id, area_id, name, description, location_payload, severity, reporter_name, reporter_mobile, created_at
FROM affected_area_reports
WHERE id = $1
`

func (q *Queries) GetAffectedAreaReportByID(ctx context.Context, id int64) (AffectedAreaReport, error) {
	row := q.db.QueryRow(ctx, getAffectedAreaReportByID, id)
	var i AffectedAreaReport
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Name,
		&i.Description,
		&i.LocationPayload,
		&i.Severity,
		&i.ReporterName,
		&i.ReporterMobile,
		&i.CreatedAt,
	)
	return i, err
}
