// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: affected_areas.sql

package sqlcgen

import (
	"context"
)

const createAffectedArea = `-- name: CreateAffectedArea :one
INSERT INTO affected_areas (
    name,
    description,
    disaster_id,
    location,
    geom,
    severity
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    ST_SetSRID(ST_GeomFromGeoJSON(NULLIF($5, '')), 4326),
    $6
)
RETURNING id, name, description, disaster_id, location, COALESCE(ST_AsGeoJSON(geom)::text, '') AS geometry, severity
`

type CreateAffectedAreaParams struct {
	Name        string               `json:"name"`
	Description *string              `json:"description"`
	DisasterID  int32                `json:"disaster_id"`
	Location    *string              `json:"location"`
	Column5     interface{}          `json:"column_5"`
	Severity    AffectedAreaSeverity `json:"severity"`
}

type CreateAffectedAreaRow struct {
	ID          int64                `json:"id"`
	Name        string               `json:"name"`
	Description *string              `json:"description"`
	DisasterID  int32                `json:"disaster_id"`
	Location    *string              `json:"location"`
	Geometry    interface{}          `json:"geometry"`
	Severity    AffectedAreaSeverity `json:"severity"`
}

func (q *Queries) CreateAffectedArea(ctx context.Context, arg CreateAffectedAreaParams) (CreateAffectedAreaRow, error) {
	row := q.db.QueryRow(ctx, createAffectedArea,
		arg.Name,
		arg.Description,
		arg.DisasterID,
		arg.Location,
		arg.Column5,
		arg.Severity,
	)
	var i CreateAffectedAreaRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DisasterID,
		&i.Location,
		&i.Geometry,
		&i.Severity,
	)
	return i, err
}
