// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: command_centers.sql

package sqlcgen

import (
	"context"
)

const createCommandCenter = `-- name: CreateCommandCenter :one
INSERT INTO command_centers (
    name,
    type,
    description,
    contact_person,
    contact_mobile,
    contact_email
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, type, description, contact_person, contact_mobile, contact_email, created_at, updated_at
`

type CreateCommandCenterParams struct {
	Name          string            `json:"name"`
	Type          CommandCenterType `json:"type"`
	Description   *string           `json:"description"`
	ContactPerson *string           `json:"contact_person"`
	ContactMobile *string           `json:"contact_mobile"`
	ContactEmail  *string           `json:"contact_email"`
}

func (q *Queries) CreateCommandCenter(ctx context.Context, arg CreateCommandCenterParams) (CommandCenter, error) {
	row := q.db.QueryRow(ctx, createCommandCenter,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.ContactPerson,
		arg.ContactMobile,
		arg.ContactEmail,
	)
	var i CommandCenter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.ContactPerson,
		&i.ContactMobile,
		&i.ContactEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
