// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disasters.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDisaster = `-- name: CreateDisaster :one
INSERT INTO disasters (
    name,
    description,
    type,
    status,
    starts_at,
    ends_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, CURRENT_TIMESTAMP),
    $6
)
RETURNING id, name, description, type, status, starts_at, ends_at
`

type CreateDisasterParams struct {
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        DisasterType       `json:"type"`
	Status      DisasterStatus     `json:"status"`
	Column5     interface{}        `json:"column_5"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

type CreateDisasterRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        DisasterType       `json:"type"`
	Status      DisasterStatus     `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateDisaster(ctx context.Context, arg CreateDisasterParams) (CreateDisasterRow, error) {
	row := q.db.QueryRow(ctx, createDisaster,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Column5,
		arg.EndsAt,
	)
	var i CreateDisasterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const getDisaster = `-- name: GetDisaster :one
SELECT id, name, description, type, status, starts_at, ends_at
FROM disasters
WHERE id = $1
`

type GetDisasterRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        DisasterType       `json:"type"`
	Status      DisasterStatus     `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) GetDisaster(ctx context.Context, id int32) (GetDisasterRow, error) {
	row := q.db.QueryRow(ctx, getDisaster, id)
	var i GetDisasterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const listDisasters = `-- name: ListDisasters :many
SELECT id, name, description, type, status, starts_at, ends_at
FROM disasters
ORDER BY starts_at DESC
`

type ListDisastersRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        DisasterType       `json:"type"`
	Status      DisasterStatus     `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) ListDisasters(ctx context.Context) ([]ListDisastersRow, error) {
	rows, err := q.db.Query(ctx, listDisasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisastersRow{}
	for rows.Next() {
		var i ListDisastersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
