// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disasters.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDisaster = `-- name: CreateDisaster :one
INSERT INTO disasters (
    name,
    description,
    type,
    status,
    starts_at,
    ends_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, CURRENT_TIMESTAMP),
    $6
)
RETURNING id, name, description, type, status, starts_at, ends_at
`

type CreateDisasterParams struct {
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        DisasterType       `json:"type"`
	Status      DisasterStatus     `json:"status"`
	Column5     interface{}        `json:"column_5"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

type CreateDisasterRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        DisasterType       `json:"type"`
	Status      DisasterStatus     `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateDisaster(ctx context.Context, arg CreateDisasterParams) (CreateDisasterRow, error) {
	row := q.db.QueryRow(ctx, createDisaster,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Column5,
		arg.EndsAt,
	)
	var i CreateDisasterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}
