// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AffectedAreaSeverity string

const (
	AffectedAreaSeverityLow      AffectedAreaSeverity = "low"
	AffectedAreaSeverityMedium   AffectedAreaSeverity = "medium"
	AffectedAreaSeverityHigh     AffectedAreaSeverity = "high"
	AffectedAreaSeverityCritical AffectedAreaSeverity = "critical"
)

func (e *AffectedAreaSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AffectedAreaSeverity(s)
	case string:
		*e = AffectedAreaSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AffectedAreaSeverity: %T", src)
	}
	return nil
}

type NullAffectedAreaSeverity struct {
	AffectedAreaSeverity AffectedAreaSeverity `json:"affected_area_severity"`
	Valid                bool                 `json:"valid"` // Valid is true if AffectedAreaSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAffectedAreaSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AffectedAreaSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AffectedAreaSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAffectedAreaSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AffectedAreaSeverity), nil
}

type AffectedAreaVerificationStatus string

const (
	AffectedAreaVerificationStatusReported      AffectedAreaVerificationStatus = "reported"
	AffectedAreaVerificationStatusInvestigating AffectedAreaVerificationStatus = "investigating"
	AffectedAreaVerificationStatusVerified      AffectedAreaVerificationStatus = "verified"
	AffectedAreaVerificationStatusDisputed      AffectedAreaVerificationStatus = "disputed"
	AffectedAreaVerificationStatusResolved      AffectedAreaVerificationStatus = "resolved"
)

func (e *AffectedAreaVerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AffectedAreaVerificationStatus(s)
	case string:
		*e = AffectedAreaVerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AffectedAreaVerificationStatus: %T", src)
	}
	return nil
}

type NullAffectedAreaVerificationStatus struct {
	AffectedAreaVerificationStatus AffectedAreaVerificationStatus `json:"affected_area_verification_status"`
	Valid                          bool                           `json:"valid"` // Valid is true if AffectedAreaVerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAffectedAreaVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AffectedAreaVerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AffectedAreaVerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAffectedAreaVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AffectedAreaVerificationStatus), nil
}

type DisasterStatus string

const (
	DisasterStatusActive   DisasterStatus = "active"
	DisasterStatusResolved DisasterStatus = "resolved"
)

func (e *DisasterStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisasterStatus(s)
	case string:
		*e = DisasterStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DisasterStatus: %T", src)
	}
	return nil
}

type NullDisasterStatus struct {
	DisasterStatus DisasterStatus `json:"disaster_status"`
	Valid          bool           `json:"valid"` // Valid is true if DisasterStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisasterStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DisasterStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisasterStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisasterStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisasterStatus), nil
}

type DisasterType string

const (
	DisasterTypeFlood      DisasterType = "flood"
	DisasterTypeEarthquake DisasterType = "earthquake"
	DisasterTypeLandslide  DisasterType = "landslide"
)

func (e *DisasterType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisasterType(s)
	case string:
		*e = DisasterType(s)
	default:
		return fmt.Errorf("unsupported scan type for DisasterType: %T", src)
	}
	return nil
}

type NullDisasterType struct {
	DisasterType DisasterType `json:"disaster_type"`
	Valid        bool         `json:"valid"` // Valid is true if DisasterType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisasterType) Scan(value interface{}) error {
	if value == nil {
		ns.DisasterType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisasterType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisasterType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisasterType), nil
}

type AffectedArea struct {
	ID                 int64                          `json:"id"`
	Name               string                         `json:"name"`
	Description        *string                        `json:"description"`
	DisasterID         int32                          `json:"disaster_id"`
	Location           *string                        `json:"location"`
	Geom               []byte                         `json:"geom"`
	Latitude           *float64                       `json:"latitude"`
	Longitude          *float64                       `json:"longitude"`
	Severity           AffectedAreaSeverity           `json:"severity"`
	VerificationStatus AffectedAreaVerificationStatus `json:"verification_status"`
	CreatedAt          time.Time                      `json:"created_at"`
	VerifiedAt         pgtype.Timestamptz             `json:"verified_at"`
	UpdatedAt          time.Time                      `json:"updated_at"`
}

type Disaster struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Type        DisasterType       `json:"type"`
	Status      DisasterStatus     `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}
