// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateAffectedArea(ctx context.Context, arg CreateAffectedAreaParams) (CreateAffectedAreaRow, error)
	CreateAffectedAreaReport(ctx context.Context, arg CreateAffectedAreaReportParams) (AffectedAreaReport, error)
	CreateDisaster(ctx context.Context, arg CreateDisasterParams) (CreateDisasterRow, error)
	GetAffectedAreaReportByID(ctx context.Context, id int64) (AffectedAreaReport, error)
	GetDisaster(ctx context.Context, id int32) (GetDisasterRow, error)
	IncrementReportCount(ctx context.Context, id int64) (int32, error)
	ListDisasters(ctx context.Context) ([]ListDisastersRow, error)
	UpdateAreaSeverity(ctx context.Context, arg UpdateAreaSeverityParams) (AffectedAreaSeverity, error)
}

var _ Querier = (*Queries)(nil)
