// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateAffectedArea(ctx context.Context, arg CreateAffectedAreaParams) (CreateAffectedAreaRow, error)
	CreateAffectedAreaReport(ctx context.Context, arg CreateAffectedAreaReportParams) (AffectedAreaReport, error)
	CreateCommandCenter(ctx context.Context, arg CreateCommandCenterParams) (CreateCommandCenterRow, error)
	CreateDisaster(ctx context.Context, arg CreateDisasterParams) (CreateDisasterRow, error)
	CreateSOSRequest(ctx context.Context, arg CreateSOSRequestParams) (CreateSOSRequestRow, error)
	FindSOSNearby(ctx context.Context, arg FindSOSNearbyParams) (FindSOSNearbyRow, error)
	GetAffectedArea(ctx context.Context, id int64) (GetAffectedAreaRow, error)
	GetAffectedAreaReportByID(ctx context.Context, id int64) (AffectedAreaReport, error)
	GetDisaster(ctx context.Context, id int32) (GetDisasterRow, error)
	IncrementReportCount(ctx context.Context, id int64) (int32, error)
	IncrementSOSReportCount(ctx context.Context, id int64) (IncrementSOSReportCountRow, error)
	ListAffectedAreas(ctx context.Context, arg ListAffectedAreasParams) ([]ListAffectedAreasRow, error)
	ListDisasters(ctx context.Context) ([]ListDisastersRow, error)
	ListSOSRequests(ctx context.Context, arg ListSOSRequestsParams) ([]ListSOSRequestsRow, error)
	UpdateAreaSeverity(ctx context.Context, arg UpdateAreaSeverityParams) (AffectedAreaSeverity, error)
}

var _ Querier = (*Queries)(nil)
