// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateAffectedArea(ctx context.Context, arg CreateAffectedAreaParams) (CreateAffectedAreaRow, error)
	CreateDisaster(ctx context.Context, arg CreateDisasterParams) (CreateDisasterRow, error)
	GetDisaster(ctx context.Context, id int32) (GetDisasterRow, error)
	ListDisasters(ctx context.Context) ([]ListDisastersRow, error)
}

var _ Querier = (*Queries)(nil)
