// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sos_requests.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSOSRequest = `-- name: CreateSOSRequest :one
INSERT INTO sos_requests (
    geom,
    reporter_mobile,
    message
)
VALUES (
    ST_SetSRID(ST_GeomFromGeoJSON(NULLIF($1::text, '')), 4326),
    $2,
    $3
)
RETURNING id,
          COALESCE(ST_AsGeoJSON(geom)::text, '') AS geometry,
          reporter_mobile, message, status, report_count, created_at, updated_at
`

type CreateSOSRequestParams struct {
	Column1        string  `json:"column_1"`
	ReporterMobile *string `json:"reporter_mobile"`
	Message        *string `json:"message"`
}

type CreateSOSRequestRow struct {
	ID             int64       `json:"id"`
	Geometry       interface{} `json:"geometry"`
	ReporterMobile *string     `json:"reporter_mobile"`
	Message        *string     `json:"message"`
	Status         SosStatus   `json:"status"`
	ReportCount    int32       `json:"report_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) CreateSOSRequest(ctx context.Context, arg CreateSOSRequestParams) (CreateSOSRequestRow, error) {
	row := q.db.QueryRow(ctx, createSOSRequest, arg.Column1, arg.ReporterMobile, arg.Message)
	var i CreateSOSRequestRow
	err := row.Scan(
		&i.ID,
		&i.Geometry,
		&i.ReporterMobile,
		&i.Message,
		&i.Status,
		&i.ReportCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
